# Homework - Part 2 - Gaussian NB 

We use Gaussian NB to classify the Iris data base. Specifically:

1. Load the iris database using load_iris from sklearn.datasets
2. split the data into train and test so that test size is half the data. Use random state=0
3. Use a Gaussian NB classifier to classify the test data
4. How many incorrect clasisfications do you get?
5. Print the parameters of the model

## Solution

In [1]:
#1
from sklearn.datasets import load_iris

iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data)
print(iris.target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3

In [2]:
#2
from sklearn.model_selection import train_test_split

#Data split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.5, random_state=0)

print (X_train.shape)    
print (y_train.shape) 
print (X_test.shape)

(75, 4)
(75,)
(75, 4)


In [3]:
#3
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.metrics import accuracy_score

#Fitting the model
model = GaussianNB().fit(X_train, y_train)

#Predictions on the test data
y_pred = model.predict(X_test)

#Evaluating the Model
print('Model accuracy on test set: %.3f%%' % (100*np.mean(y_pred == y_test)))
accuracy = accuracy_score(y_test, y_pred)

Model accuracy on test set: 94.667%


In [4]:
#4
#Incorrect classifications
num_incorrect = np.sum(y_test != y_pred)
print('Number of incorrect classifications:' ,num_incorrect)

#Double check 
#print('Number of incorrect classifications', round((1-accuracy) * len(y_test)))

Number of incorrect classifications: 4


In [5]:
#5
print("model.get_params():\n", model.get_params())
print("\nmodel.theta_:\n", model.theta_)
print("\nmodel.var_:\n", model.var_)
print("\nmodel.class_prior_:\n", model.class_prior_)

model.get_params():
 {'priors': None, 'var_smoothing': 1e-09}

model.theta_:
 [[4.97586207 3.35862069 1.44827586 0.23448276]
 [5.935      2.71       4.185      1.3       ]
 [6.77692308 3.09230769 5.73461538 2.10769231]]

model.var_:
 [[0.10321047 0.13208086 0.01629013 0.00846612]
 [0.256275   0.0829     0.255275   0.046     ]
 [0.38869823 0.10147929 0.31303255 0.04763314]]

model.class_prior_:
 [0.38666667 0.26666667 0.34666667]
